# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppblog', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppblog.Topic'),
            preserve_default=False,
        ),
    ]
